---
- name: Import repository GPG key
  shell:
    "curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg"

- name: To configure PostgreSQL repository
  shell: sudo sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

- name: Update apt cache after adding PostgreSQL repo
  apt:
    update_cache: yes

- name: Install PostgreSQL
  apt:
    name: postgresql-16
    state: present

- name: Ensure PostgreSQL is started and enabled
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Allow to listen all adresses
  shell: postgres -c listen_addresses='*'

- name: Change pg_hba.conf
  copy:
    src: pg_hba.conf
    dest: /etc/postgresql/16/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0644'

- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted